apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openvpns.ptlc.nl
spec:
  group: ptlc.nl
  names:
    kind: OpenVPN
    listKind: OpenVPNList
    plural: openvpns
    singular: openvpn
  scope: Namespaced
  version: v1alpha1
