apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openvpn-operator
  template:
    metadata:
      labels:
        name: openvpn-operator
    spec:
      containers:
        - name: openvpn-operator
          image: test
          command:
          - openvpn-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
