kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openvpn-operator
rules:
- apiGroups:
  - ptlc.nl
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-openvpn-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: openvpn-operator
  apiGroup: rbac.authorization.k8s.io
